name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v1
      with:
        submodules: true
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install workload
      run: dotnet workload install wasm-tools

    - name: Build Debug
      run: dotnet build Trains.NET.sln -p:CI=true -c Debug

    - name: Build Release
      run: dotnet build Trains.NET.sln -p:CI=true -c Release -bl

    - name: Upload binary log
      uses: actions/upload-artifact@v2
      with:
        name: binlog
        path: msbuild.binlog
        retention-days: 5

    - name: Run tests
      run: dotnet test
